url: https://y7kim.github.io
baseurl: ""

# Site settings
title: David Schnitzhofer
email: david@schnitzhofer.at
description: "Willkommen auf meinem Portfolio! Hier findest du meine FÃ¤higkeiten und einen Auszug meiner Projekte aus den Bereichen Mobile Entwicklung, Design und interaktive Systeme."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/dvschnitz

# Postal address (add as many lines as necessary)
address:
  - line: Markt
  - line: 5441 Abtenau

# Build settings
markdown: kramdown
permalink: pretty
